### ISSUE TITLE
Question: How to build the bootloader with Segger Embedded Studio?

### ISSUE THREAD

**Issue by beegee-tokyo** [adafruit/Adafruit_nRF52_Arduino_Bootloader#13]
I am trying to build this bootloader with the Segger Embedded Studio.
I imported the project into the Studio and compile it without errors. But there is no **__build_** folder in **_src_** after the build finished.
But in the **_segger_** folder is an **_Output_** with two subdirectories. But I cannot find any **_.hex_** file. There are a lot of **_.o_** files, and a **_.elf_** and a **_.map_** file.

Am I missing something? How are the bootloader and the softdevice linked together to a flashable hex file with Segger?

**Comment by hathach** [comment]
development is moved to https://github.com/adafruit/Adafruit_nRF52_Bootloader, this repo is obsolete
