### ISSUE TITLE
Setup DTR Toggling via CP210x

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_nRF52_Arduino_Bootloader#3]
A simple GCC based C executable should be generated to test toggling the DTR Line on the CP2104. The following sample code seems to be a decent starting point: http://community.silabs.com/t5/Interface/CP2104-Linux-code-to-set-state-of-DTR-pin/td-p/138733

**Comment by Chandra405Chinna** [comment]
How can I change the above code to toggle continuously per second based on the input frequency given??
